services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: pass
    volumes:
      - data-volume:/data/db

volumes:
  data-volume: